# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'uiMainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.2.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QGridLayout, QHBoxLayout, QHeaderView, QLabel,
    QMainWindow, QMenu, QMenuBar, QProgressBar,
    QPushButton, QSizePolicy, QSpacerItem, QSpinBox,
    QStatusBar, QTabWidget, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(871, 648)
        icon = QIcon()
        icon.addFile(u"src/img/QIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.action.setCheckable(True)
        self.action.setChecked(True)
        self.action_open = QAction(MainWindow)
        self.action_open.setObjectName(u"action_open")
        icon1 = QIcon()
        icon1.addFile(u"src/img/Open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_open.setIcon(icon1)
        self.action_check_update = QAction(MainWindow)
        self.action_check_update.setObjectName(u"action_check_update")
        icon2 = QIcon()
        icon2.addFile(u"src/img/Clockwise.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_check_update.setIcon(icon2)
        self.action_table = QAction(MainWindow)
        self.action_table.setObjectName(u"action_table")
        self.action_table.setEnabled(False)
        self.action_wordCloudImage = QAction(MainWindow)
        self.action_wordCloudImage.setObjectName(u"action_wordCloudImage")
        self.action_wordCloudImage.setEnabled(False)
        self.action_about = QAction(MainWindow)
        self.action_about.setObjectName(u"action_about")
        icon3 = QIcon()
        icon3.addFile(u"src/img/Information.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_about.setIcon(icon3)
        self.actionJVM = QAction(MainWindow)
        self.actionJVM.setObjectName(u"actionJVM")
        icon4 = QIcon()
        icon4.addFile(u"src/img/JVM.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionJVM.setIcon(icon4)
        self.action_preference = QAction(MainWindow)
        self.action_preference.setObjectName(u"action_preference")
        icon5 = QIcon()
        icon5.addFile(u"src/img/Setting.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_preference.setIcon(icon5)
        self.action_textCleaningSetting = QAction(MainWindow)
        self.action_textCleaningSetting.setObjectName(u"action_textCleaningSetting")
        self.action_textCleaningSetting.setCheckable(True)
        self.action_textCleaningSetting.setChecked(False)
        self.action_textMiningSetting = QAction(MainWindow)
        self.action_textMiningSetting.setObjectName(u"action_textMiningSetting")
        self.action_textMiningSetting.setCheckable(True)
        self.action_cutWordSetting = QAction(MainWindow)
        self.action_cutWordSetting.setObjectName(u"action_cutWordSetting")
        self.action_cutWordSetting.setCheckable(True)
        self.action_wordCloudSetting = QAction(MainWindow)
        self.action_wordCloudSetting.setObjectName(u"action_wordCloudSetting")
        self.action_wordCloudSetting.setCheckable(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_6 = QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.horizontalLayout_20 = QHBoxLayout()
        self.horizontalLayout_20.setObjectName(u"horizontalLayout_20")
        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_20.addItem(self.horizontalSpacer_3)

        self.pushButton_UpTop = QPushButton(self.centralwidget)
        self.pushButton_UpTop.setObjectName(u"pushButton_UpTop")
        self.pushButton_UpTop.setMinimumSize(QSize(30, 25))
        self.pushButton_UpTop.setMaximumSize(QSize(30, 25))
        icon6 = QIcon()
        icon6.addFile(u"src/img/Head.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_UpTop.setIcon(icon6)

        self.horizontalLayout_20.addWidget(self.pushButton_UpTop)

        self.pushButton_Up = QPushButton(self.centralwidget)
        self.pushButton_Up.setObjectName(u"pushButton_Up")
        self.pushButton_Up.setMinimumSize(QSize(30, 25))
        self.pushButton_Up.setMaximumSize(QSize(30, 25))
        icon7 = QIcon()
        icon7.addFile(u"src/img/Up.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_Up.setIcon(icon7)
        self.pushButton_Up.setAutoRepeat(True)
        self.pushButton_Up.setAutoRepeatDelay(500)

        self.horizontalLayout_20.addWidget(self.pushButton_Up)

        self.spinBox_pageNow = QSpinBox(self.centralwidget)
        self.spinBox_pageNow.setObjectName(u"spinBox_pageNow")
        self.spinBox_pageNow.setMinimumSize(QSize(30, 25))
        self.spinBox_pageNow.setMaximumSize(QSize(16777215, 25))
        self.spinBox_pageNow.setLayoutDirection(Qt.LeftToRight)
        self.spinBox_pageNow.setStyleSheet(u"background:transparent;")
        self.spinBox_pageNow.setWrapping(False)
        self.spinBox_pageNow.setFrame(False)
        self.spinBox_pageNow.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.spinBox_pageNow.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spinBox_pageNow.setProperty("showGroupSeparator", False)
        self.spinBox_pageNow.setMinimum(1)
        self.spinBox_pageNow.setMaximum(10000)

        self.horizontalLayout_20.addWidget(self.spinBox_pageNow)

        self.label_pageMax = QLabel(self.centralwidget)
        self.label_pageMax.setObjectName(u"label_pageMax")
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pageMax.sizePolicy().hasHeightForWidth())
        self.label_pageMax.setSizePolicy(sizePolicy)
        self.label_pageMax.setMinimumSize(QSize(30, 25))
        self.label_pageMax.setMaximumSize(QSize(16777215, 25))

        self.horizontalLayout_20.addWidget(self.label_pageMax)

        self.spinBox_everyPage = QSpinBox(self.centralwidget)
        self.spinBox_everyPage.setObjectName(u"spinBox_everyPage")
        self.spinBox_everyPage.setMinimumSize(QSize(30, 25))
        self.spinBox_everyPage.setMaximumSize(QSize(16777215, 25))
        self.spinBox_everyPage.setLayoutDirection(Qt.LeftToRight)
        self.spinBox_everyPage.setStyleSheet(u"background:transparent;")
        self.spinBox_everyPage.setWrapping(False)
        self.spinBox_everyPage.setFrame(False)
        self.spinBox_everyPage.setAlignment(Qt.AlignCenter)
        self.spinBox_everyPage.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spinBox_everyPage.setProperty("showGroupSeparator", False)
        self.spinBox_everyPage.setMinimum(100)
        self.spinBox_everyPage.setMaximum(1000)
        self.spinBox_everyPage.setSingleStep(50)
        self.spinBox_everyPage.setValue(100)

        self.horizontalLayout_20.addWidget(self.spinBox_everyPage)

        self.label_pageMax_2 = QLabel(self.centralwidget)
        self.label_pageMax_2.setObjectName(u"label_pageMax_2")
        sizePolicy.setHeightForWidth(self.label_pageMax_2.sizePolicy().hasHeightForWidth())
        self.label_pageMax_2.setSizePolicy(sizePolicy)
        self.label_pageMax_2.setMinimumSize(QSize(30, 25))
        self.label_pageMax_2.setMaximumSize(QSize(16777215, 25))

        self.horizontalLayout_20.addWidget(self.label_pageMax_2)

        self.pushButton_Down = QPushButton(self.centralwidget)
        self.pushButton_Down.setObjectName(u"pushButton_Down")
        self.pushButton_Down.setMinimumSize(QSize(30, 25))
        self.pushButton_Down.setMaximumSize(QSize(30, 25))
        icon8 = QIcon()
        icon8.addFile(u"src/img/Next.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_Down.setIcon(icon8)
        self.pushButton_Down.setAutoRepeat(True)
        self.pushButton_Down.setAutoRepeatDelay(500)

        self.horizontalLayout_20.addWidget(self.pushButton_Down)

        self.pushButton_DownTop = QPushButton(self.centralwidget)
        self.pushButton_DownTop.setObjectName(u"pushButton_DownTop")
        self.pushButton_DownTop.setMinimumSize(QSize(30, 25))
        self.pushButton_DownTop.setMaximumSize(QSize(30, 25))
        icon9 = QIcon()
        icon9.addFile(u"src/img/End.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_DownTop.setIcon(icon9)

        self.horizontalLayout_20.addWidget(self.pushButton_DownTop)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_20.addItem(self.horizontalSpacer_4)


        self.gridLayout_6.addLayout(self.horizontalLayout_20, 4, 0, 1, 1)

        self.tableWidget = QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(u"tableWidget")

        self.gridLayout_6.addWidget(self.tableWidget, 3, 0, 1, 1)

        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setMinimumSize(QSize(0, 25))
        self.tabWidget.setMaximumSize(QSize(16777215, 25))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QTabWidget.South)
        self.tabWidget.setTabBarAutoHide(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget.addTab(self.tab, "")

        self.gridLayout_6.addWidget(self.tabWidget, 5, 0, 1, 1)

        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setMinimumSize(QSize(0, 25))
        self.progressBar.setMaximumSize(QSize(16777215, 25))
        self.progressBar.setValue(0)

        self.gridLayout_6.addWidget(self.progressBar, 2, 0, 1, 1)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.comboBox_selectColumn = QComboBox(self.centralwidget)
        self.comboBox_selectColumn.addItem("")
        self.comboBox_selectColumn.setObjectName(u"comboBox_selectColumn")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.comboBox_selectColumn.sizePolicy().hasHeightForWidth())
        self.comboBox_selectColumn.setSizePolicy(sizePolicy1)
        self.comboBox_selectColumn.setMinimumSize(QSize(0, 35))
        self.comboBox_selectColumn.setMaximumSize(QSize(16777215, 35))
        font = QFont()
        font.setPointSize(9)
        self.comboBox_selectColumn.setFont(font)

        self.horizontalLayout.addWidget(self.comboBox_selectColumn)

        self.pushButton_start = QPushButton(self.centralwidget)
        self.pushButton_start.setObjectName(u"pushButton_start")
        sizePolicy1.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy1)
        self.pushButton_start.setMinimumSize(QSize(90, 35))
        self.pushButton_start.setMaximumSize(QSize(90, 35))
        icon10 = QIcon()
        icon10.addFile(u"src/img/Run.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_start.setIcon(icon10)

        self.horizontalLayout.addWidget(self.pushButton_start)


        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.tabWidget_modelChoice = QTabWidget(self.centralwidget)
        self.tabWidget_modelChoice.setObjectName(u"tabWidget_modelChoice")
        self.tabWidget_modelChoice.setMaximumSize(QSize(16777215, 125))
        self.tabWidget_modelChoice.setFont(font)
        self.tab_0 = QWidget()
        self.tab_0.setObjectName(u"tab_0")
        self.gridLayout = QGridLayout(self.tab_0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.checkBox_Chinese = QCheckBox(self.tab_0)
        self.checkBox_Chinese.setObjectName(u"checkBox_Chinese")
        self.checkBox_Chinese.setFont(font)
        self.checkBox_Chinese.setChecked(True)

        self.gridLayout_3.addWidget(self.checkBox_Chinese, 0, 0, 1, 1)

        self.checkBox_ChinesePunctuation = QCheckBox(self.tab_0)
        self.checkBox_ChinesePunctuation.setObjectName(u"checkBox_ChinesePunctuation")
        self.checkBox_ChinesePunctuation.setFont(font)

        self.gridLayout_3.addWidget(self.checkBox_ChinesePunctuation, 0, 1, 1, 1)

        self.checkBox_Number = QCheckBox(self.tab_0)
        self.checkBox_Number.setObjectName(u"checkBox_Number")
        self.checkBox_Number.setFont(font)

        self.gridLayout_3.addWidget(self.checkBox_Number, 0, 2, 1, 1)

        self.checkBox_EnglishUpper = QCheckBox(self.tab_0)
        self.checkBox_EnglishUpper.setObjectName(u"checkBox_EnglishUpper")
        self.checkBox_EnglishUpper.setFont(font)

        self.gridLayout_3.addWidget(self.checkBox_EnglishUpper, 1, 0, 1, 1)

        self.checkBox_EnglishLower = QCheckBox(self.tab_0)
        self.checkBox_EnglishLower.setObjectName(u"checkBox_EnglishLower")
        self.checkBox_EnglishLower.setFont(font)

        self.gridLayout_3.addWidget(self.checkBox_EnglishLower, 1, 1, 1, 1)

        self.checkBox_EnglishPunctuation = QCheckBox(self.tab_0)
        self.checkBox_EnglishPunctuation.setObjectName(u"checkBox_EnglishPunctuation")
        self.checkBox_EnglishPunctuation.setFont(font)

        self.gridLayout_3.addWidget(self.checkBox_EnglishPunctuation, 1, 2, 1, 1)


        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.pushButton_textCleaningSetting = QPushButton(self.tab_0)
        self.pushButton_textCleaningSetting.setObjectName(u"pushButton_textCleaningSetting")
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pushButton_textCleaningSetting.sizePolicy().hasHeightForWidth())
        self.pushButton_textCleaningSetting.setSizePolicy(sizePolicy2)
        self.pushButton_textCleaningSetting.setMinimumSize(QSize(120, 35))
        self.pushButton_textCleaningSetting.setMaximumSize(QSize(120, 30))
        self.pushButton_textCleaningSetting.setFont(font)
        self.pushButton_textCleaningSetting.setIcon(icon5)

        self.gridLayout.addWidget(self.pushButton_textCleaningSetting, 0, 1, 1, 1)

        self.tabWidget_modelChoice.addTab(self.tab_0, "")
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.gridLayout_5 = QGridLayout(self.tab_1)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.label_2 = QLabel(self.tab_1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMinimumSize(QSize(0, 40))
        self.label_2.setMaximumSize(QSize(16777215, 40))
        self.label_2.setFont(font)

        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)

        self.spinBox_wordMining = QSpinBox(self.tab_1)
        self.spinBox_wordMining.setObjectName(u"spinBox_wordMining")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.spinBox_wordMining.sizePolicy().hasHeightForWidth())
        self.spinBox_wordMining.setSizePolicy(sizePolicy3)
        self.spinBox_wordMining.setMinimumSize(QSize(60, 35))
        self.spinBox_wordMining.setMaximumSize(QSize(60, 35))
        self.spinBox_wordMining.setFont(font)
        self.spinBox_wordMining.setMinimum(2)
        self.spinBox_wordMining.setValue(4)

        self.gridLayout_5.addWidget(self.spinBox_wordMining, 0, 1, 1, 1)

        self.pushButton_wordMiningSetting = QPushButton(self.tab_1)
        self.pushButton_wordMiningSetting.setObjectName(u"pushButton_wordMiningSetting")
        sizePolicy2.setHeightForWidth(self.pushButton_wordMiningSetting.sizePolicy().hasHeightForWidth())
        self.pushButton_wordMiningSetting.setSizePolicy(sizePolicy2)
        self.pushButton_wordMiningSetting.setMinimumSize(QSize(120, 35))
        self.pushButton_wordMiningSetting.setMaximumSize(QSize(120, 35))
        self.pushButton_wordMiningSetting.setFont(font)
        self.pushButton_wordMiningSetting.setIcon(icon5)

        self.gridLayout_5.addWidget(self.pushButton_wordMiningSetting, 0, 2, 1, 1)

        self.horizontalSpacer = QSpacerItem(606, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_5.addItem(self.horizontalSpacer, 0, 3, 1, 1)

        self.tabWidget_modelChoice.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.gridLayout_4 = QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.pushButton_cutWordSetting = QPushButton(self.tab_2)
        self.pushButton_cutWordSetting.setObjectName(u"pushButton_cutWordSetting")
        sizePolicy2.setHeightForWidth(self.pushButton_cutWordSetting.sizePolicy().hasHeightForWidth())
        self.pushButton_cutWordSetting.setSizePolicy(sizePolicy2)
        self.pushButton_cutWordSetting.setMinimumSize(QSize(120, 35))
        self.pushButton_cutWordSetting.setMaximumSize(QSize(120, 35))
        self.pushButton_cutWordSetting.setFont(font)
        self.pushButton_cutWordSetting.setIcon(icon5)

        self.gridLayout_4.addWidget(self.pushButton_cutWordSetting, 0, 5, 1, 1)

        self.spinBox_cutModelExtraction = QSpinBox(self.tab_2)
        self.spinBox_cutModelExtraction.setObjectName(u"spinBox_cutModelExtraction")
        self.spinBox_cutModelExtraction.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.spinBox_cutModelExtraction.sizePolicy().hasHeightForWidth())
        self.spinBox_cutModelExtraction.setSizePolicy(sizePolicy1)
        self.spinBox_cutModelExtraction.setMinimumSize(QSize(70, 35))
        self.spinBox_cutModelExtraction.setMaximumSize(QSize(70, 35))
        self.spinBox_cutModelExtraction.setFont(font)
        self.spinBox_cutModelExtraction.setMinimum(1)
        self.spinBox_cutModelExtraction.setValue(5)

        self.gridLayout_4.addWidget(self.spinBox_cutModelExtraction, 0, 3, 1, 1)

        self.comboBox_cutWordModelSelect = QComboBox(self.tab_2)
        self.comboBox_cutWordModelSelect.addItem("")
        self.comboBox_cutWordModelSelect.addItem("")
        self.comboBox_cutWordModelSelect.addItem("")
        self.comboBox_cutWordModelSelect.addItem("")
        self.comboBox_cutWordModelSelect.addItem("")
        self.comboBox_cutWordModelSelect.addItem("")
        self.comboBox_cutWordModelSelect.setObjectName(u"comboBox_cutWordModelSelect")
        sizePolicy1.setHeightForWidth(self.comboBox_cutWordModelSelect.sizePolicy().hasHeightForWidth())
        self.comboBox_cutWordModelSelect.setSizePolicy(sizePolicy1)
        self.comboBox_cutWordModelSelect.setMinimumSize(QSize(0, 35))
        self.comboBox_cutWordModelSelect.setMaximumSize(QSize(16777215, 35))
        self.comboBox_cutWordModelSelect.setFont(font)

        self.gridLayout_4.addWidget(self.comboBox_cutWordModelSelect, 0, 1, 1, 1)

        self.label_cutModelExtraction = QLabel(self.tab_2)
        self.label_cutModelExtraction.setObjectName(u"label_cutModelExtraction")
        self.label_cutModelExtraction.setMinimumSize(QSize(90, 40))
        self.label_cutModelExtraction.setMaximumSize(QSize(90, 40))
        self.label_cutModelExtraction.setFont(font)

        self.gridLayout_4.addWidget(self.label_cutModelExtraction, 0, 2, 1, 1)

        self.label = QLabel(self.tab_2)
        self.label.setObjectName(u"label")
        self.label.setMinimumSize(QSize(110, 40))
        self.label.setMaximumSize(QSize(110, 40))
        self.label.setFont(font)

        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)

        self.checkBox_wordFrequency = QCheckBox(self.tab_2)
        self.checkBox_wordFrequency.setObjectName(u"checkBox_wordFrequency")
        self.checkBox_wordFrequency.setMinimumSize(QSize(110, 40))
        self.checkBox_wordFrequency.setMaximumSize(QSize(110, 40))
        self.checkBox_wordFrequency.setChecked(True)

        self.gridLayout_4.addWidget(self.checkBox_wordFrequency, 0, 4, 1, 1)

        self.tabWidget_modelChoice.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.gridLayout_2 = QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.label_8 = QLabel(self.tab_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setMinimumSize(QSize(90, 40))
        self.label_8.setMaximumSize(QSize(90, 40))
        self.label_8.setFont(font)

        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)

        self.spinBox_textClusteringParam = QSpinBox(self.tab_3)
        self.spinBox_textClusteringParam.setObjectName(u"spinBox_textClusteringParam")
        self.spinBox_textClusteringParam.setMinimumSize(QSize(70, 35))
        self.spinBox_textClusteringParam.setMaximumSize(QSize(70, 35))
        self.spinBox_textClusteringParam.setMinimum(2)
        self.spinBox_textClusteringParam.setMaximum(9999)

        self.gridLayout_2.addWidget(self.spinBox_textClusteringParam, 0, 3, 1, 1)

        self.comboBox_textClusteringModelSelect = QComboBox(self.tab_3)
        self.comboBox_textClusteringModelSelect.addItem("")
        self.comboBox_textClusteringModelSelect.addItem("")
        self.comboBox_textClusteringModelSelect.addItem("")
        self.comboBox_textClusteringModelSelect.setObjectName(u"comboBox_textClusteringModelSelect")
        sizePolicy1.setHeightForWidth(self.comboBox_textClusteringModelSelect.sizePolicy().hasHeightForWidth())
        self.comboBox_textClusteringModelSelect.setSizePolicy(sizePolicy1)
        self.comboBox_textClusteringModelSelect.setMinimumSize(QSize(0, 35))
        self.comboBox_textClusteringModelSelect.setMaximumSize(QSize(16777215, 35))
        self.comboBox_textClusteringModelSelect.setFont(font)

        self.gridLayout_2.addWidget(self.comboBox_textClusteringModelSelect, 0, 1, 1, 1)

        self.label_7 = QLabel(self.tab_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setMinimumSize(QSize(110, 40))
        self.label_7.setMaximumSize(QSize(110, 40))
        self.label_7.setFont(font)

        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer_2, 0, 4, 1, 1)

        self.tabWidget_modelChoice.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.gridLayout_7 = QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.label_4 = QLabel(self.tab_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setMinimumSize(QSize(80, 35))
        self.label_4.setMaximumSize(QSize(80, 35))
        self.label_4.setFont(font)

        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)

        self.comboBox_wordCloudText = QComboBox(self.tab_4)
        self.comboBox_wordCloudText.addItem("")
        self.comboBox_wordCloudText.setObjectName(u"comboBox_wordCloudText")
        sizePolicy1.setHeightForWidth(self.comboBox_wordCloudText.sizePolicy().hasHeightForWidth())
        self.comboBox_wordCloudText.setSizePolicy(sizePolicy1)
        self.comboBox_wordCloudText.setMinimumSize(QSize(0, 35))
        self.comboBox_wordCloudText.setMaximumSize(QSize(16777215, 35))
        self.comboBox_wordCloudText.setFont(font)

        self.gridLayout_7.addWidget(self.comboBox_wordCloudText, 0, 1, 1, 1)

        self.label_6 = QLabel(self.tab_4)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setMinimumSize(QSize(50, 35))
        self.label_6.setMaximumSize(QSize(50, 35))
        self.label_6.setFont(font)

        self.gridLayout_7.addWidget(self.label_6, 0, 2, 1, 1)

        self.spinBox_wordCloudImgWidth = QSpinBox(self.tab_4)
        self.spinBox_wordCloudImgWidth.setObjectName(u"spinBox_wordCloudImgWidth")
        self.spinBox_wordCloudImgWidth.setMinimumSize(QSize(80, 35))
        self.spinBox_wordCloudImgWidth.setMaximumSize(QSize(80, 35))
        self.spinBox_wordCloudImgWidth.setMinimum(400)
        self.spinBox_wordCloudImgWidth.setMaximum(4096)
        self.spinBox_wordCloudImgWidth.setValue(400)

        self.gridLayout_7.addWidget(self.spinBox_wordCloudImgWidth, 0, 3, 1, 1)

        self.pushButton_wordCloudSetting = QPushButton(self.tab_4)
        self.pushButton_wordCloudSetting.setObjectName(u"pushButton_wordCloudSetting")
        sizePolicy2.setHeightForWidth(self.pushButton_wordCloudSetting.sizePolicy().hasHeightForWidth())
        self.pushButton_wordCloudSetting.setSizePolicy(sizePolicy2)
        self.pushButton_wordCloudSetting.setMinimumSize(QSize(120, 35))
        self.pushButton_wordCloudSetting.setMaximumSize(QSize(120, 35))
        self.pushButton_wordCloudSetting.setFont(font)
        self.pushButton_wordCloudSetting.setIcon(icon5)

        self.gridLayout_7.addWidget(self.pushButton_wordCloudSetting, 0, 4, 1, 2)

        self.label_5 = QLabel(self.tab_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMinimumSize(QSize(80, 35))
        self.label_5.setMaximumSize(QSize(80, 35))
        self.label_5.setFont(font)

        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)

        self.comboBox_wordCloudRank = QComboBox(self.tab_4)
        self.comboBox_wordCloudRank.addItem("")
        self.comboBox_wordCloudRank.setObjectName(u"comboBox_wordCloudRank")
        sizePolicy1.setHeightForWidth(self.comboBox_wordCloudRank.sizePolicy().hasHeightForWidth())
        self.comboBox_wordCloudRank.setSizePolicy(sizePolicy1)
        self.comboBox_wordCloudRank.setMinimumSize(QSize(0, 35))
        self.comboBox_wordCloudRank.setMaximumSize(QSize(16777215, 35))
        self.comboBox_wordCloudRank.setFont(font)

        self.gridLayout_7.addWidget(self.comboBox_wordCloudRank, 1, 1, 1, 1)

        self.label_9 = QLabel(self.tab_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setMinimumSize(QSize(50, 35))
        self.label_9.setMaximumSize(QSize(50, 35))
        self.label_9.setFont(font)

        self.gridLayout_7.addWidget(self.label_9, 1, 2, 1, 1)

        self.spinBox_wordCloudImgHeight = QSpinBox(self.tab_4)
        self.spinBox_wordCloudImgHeight.setObjectName(u"spinBox_wordCloudImgHeight")
        self.spinBox_wordCloudImgHeight.setMinimumSize(QSize(80, 35))
        self.spinBox_wordCloudImgHeight.setMaximumSize(QSize(80, 35))
        self.spinBox_wordCloudImgHeight.setMinimum(300)
        self.spinBox_wordCloudImgHeight.setMaximum(2160)
        self.spinBox_wordCloudImgHeight.setSingleStep(1)
        self.spinBox_wordCloudImgHeight.setValue(300)

        self.gridLayout_7.addWidget(self.spinBox_wordCloudImgHeight, 1, 3, 1, 1)

        self.pushButton_makeWordCloud = QPushButton(self.tab_4)
        self.pushButton_makeWordCloud.setObjectName(u"pushButton_makeWordCloud")
        self.pushButton_makeWordCloud.setMinimumSize(QSize(90, 35))
        self.pushButton_makeWordCloud.setMaximumSize(QSize(90, 35))
        icon11 = QIcon()
        icon11.addFile(u"src/img/Pencil.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_makeWordCloud.setIcon(icon11)

        self.gridLayout_7.addWidget(self.pushButton_makeWordCloud, 1, 4, 1, 1)

        self.pushButton_viewWordCloud = QPushButton(self.tab_4)
        self.pushButton_viewWordCloud.setObjectName(u"pushButton_viewWordCloud")
        sizePolicy1.setHeightForWidth(self.pushButton_viewWordCloud.sizePolicy().hasHeightForWidth())
        self.pushButton_viewWordCloud.setSizePolicy(sizePolicy1)
        self.pushButton_viewWordCloud.setMinimumSize(QSize(90, 35))
        self.pushButton_viewWordCloud.setMaximumSize(QSize(90, 35))
        icon12 = QIcon()
        icon12.addFile(u"src/img/Preview.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_viewWordCloud.setIcon(icon12)

        self.gridLayout_7.addWidget(self.pushButton_viewWordCloud, 1, 5, 1, 1)

        self.tabWidget_modelChoice.addTab(self.tab_4, "")

        self.gridLayout_6.addWidget(self.tabWidget_modelChoice, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 871, 22))
        self.file_menu = QMenu(self.menubar)
        self.file_menu.setObjectName(u"file_menu")
        self.menu_save = QMenu(self.file_menu)
        self.menu_save.setObjectName(u"menu_save")
        self.menu_save.setEnabled(True)
        icon13 = QIcon()
        icon13.addFile(u"src/img/Export.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_save.setIcon(icon13)
        self.menu_table = QMenu(self.menu_save)
        self.menu_table.setObjectName(u"menu_table")
        self.menu_table.setEnabled(True)
        icon14 = QIcon()
        icon14.addFile(u"src/img/Table.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_table.setIcon(icon14)
        self.menu_image = QMenu(self.menu_save)
        self.menu_image.setObjectName(u"menu_image")
        self.menu_image.setEnabled(True)
        icon15 = QIcon()
        icon15.addFile(u"src/img/Photos.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_image.setIcon(icon15)
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_3 = QMenu(self.menubar)
        self.menu_3.setObjectName(u"menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.file_menu.addAction(self.action_open)
        self.file_menu.addAction(self.menu_save.menuAction())
        self.menu_save.addAction(self.menu_table.menuAction())
        self.menu_save.addAction(self.menu_image.menuAction())
        self.menu_table.addAction(self.action_table)
        self.menu_image.addAction(self.action_wordCloudImage)
        self.menu_2.addAction(self.action_check_update)
        self.menu_2.addAction(self.action_about)
        self.menu.addAction(self.action_preference)
        self.menu.addAction(self.actionJVM)
        self.menu_3.addAction(self.action_textCleaningSetting)
        self.menu_3.addAction(self.action_textMiningSetting)
        self.menu_3.addAction(self.action_cutWordSetting)
        self.menu_3.addAction(self.action_wordCloudSetting)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_modelChoice.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Text Tools", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u6587\u672c\u6e05\u6d17", None))
        self.action_open.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
        self.action_check_update.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u67e5\u66f4\u65b0", None))
        self.action_table.setText(QCoreApplication.translate("MainWindow", u"\u65e0\u6570\u636e\u53ef\u4fdd\u5b58", None))
        self.action_wordCloudImage.setText(QCoreApplication.translate("MainWindow", u"\u65e0\u56fe\u7247\u53ef\u4fdd\u5b58", None))
        self.action_about.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.actionJVM.setText(QCoreApplication.translate("MainWindow", u"JVM\u8bbe\u7f6e", None))
        self.action_preference.setText(QCoreApplication.translate("MainWindow", u"\u9996\u9009\u9879", None))
        self.action_textCleaningSetting.setText(QCoreApplication.translate("MainWindow", u"\u6587\u672c\u6e05\u6d17\u8bbe\u7f6e", None))
        self.action_textMiningSetting.setText(QCoreApplication.translate("MainWindow", u"\u8bcd\u8bed\u6316\u6398\u8bbe\u7f6e", None))
        self.action_cutWordSetting.setText(QCoreApplication.translate("MainWindow", u"\u6587\u672c\u5206\u8bcd\u8bbe\u7f6e", None))
        self.action_wordCloudSetting.setText(QCoreApplication.translate("MainWindow", u"\u8bcd\u4e91\u56fe\u8bbe\u7f6e", None))
#if QT_CONFIG(statustip)
        self.pushButton_UpTop.setStatusTip(QCoreApplication.translate("MainWindow", u"\u9996\u9875", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pushButton_UpTop.setWhatsThis(QCoreApplication.translate("MainWindow", u"\u9996\u9875", None))
#endif // QT_CONFIG(whatsthis)
        self.pushButton_UpTop.setText("")
#if QT_CONFIG(statustip)
        self.pushButton_Up.setStatusTip(QCoreApplication.translate("MainWindow", u"\u4e0a\u4e00\u9875", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pushButton_Up.setWhatsThis(QCoreApplication.translate("MainWindow", u"\u4e0a\u4e00\u9875", None))
#endif // QT_CONFIG(whatsthis)
        self.pushButton_Up.setText("")
#if QT_CONFIG(statustip)
        self.spinBox_pageNow.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u9875\u7801", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.spinBox_pageNow.setWhatsThis(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u9875\u7801", None))
#endif // QT_CONFIG(whatsthis)
        self.label_pageMax.setText(QCoreApplication.translate("MainWindow", u"/1 (\u6bcf\u9875", None))
#if QT_CONFIG(statustip)
        self.spinBox_everyPage.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6bcf\u9875\u8bb0\u5f55", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.spinBox_everyPage.setWhatsThis(QCoreApplication.translate("MainWindow", u"\u6bcf\u9875\u8bb0\u5f55", None))
#endif // QT_CONFIG(whatsthis)
        self.label_pageMax_2.setText(QCoreApplication.translate("MainWindow", u"\u6761\u8bb0\u5f55)", None))
#if QT_CONFIG(statustip)
        self.pushButton_Down.setStatusTip(QCoreApplication.translate("MainWindow", u"\u4e0b\u4e00\u9875", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pushButton_Down.setWhatsThis(QCoreApplication.translate("MainWindow", u"\u4e0b\u4e00\u9875", None))
#endif // QT_CONFIG(whatsthis)
        self.pushButton_Down.setText("")
#if QT_CONFIG(statustip)
        self.pushButton_DownTop.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5c3e\u9875", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pushButton_DownTop.setWhatsThis(QCoreApplication.translate("MainWindow", u"\u5c3e\u9875", None))
#endif // QT_CONFIG(whatsthis)
        self.pushButton_DownTop.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.comboBox_selectColumn.setItemText(0, QCoreApplication.translate("MainWindow", u"\u8bf7\u9009\u62e9\u4e00\u5217\u6570\u636e", None))

        self.pushButton_start.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb", None))
        self.checkBox_Chinese.setText(QCoreApplication.translate("MainWindow", u"\u4e2d\u6587\u5b57\u7b26", None))
        self.checkBox_ChinesePunctuation.setText(QCoreApplication.translate("MainWindow", u"\u4e2d\u6587\u6807\u70b9", None))
        self.checkBox_Number.setText(QCoreApplication.translate("MainWindow", u"\u6570\u5b57", None))
        self.checkBox_EnglishUpper.setText(QCoreApplication.translate("MainWindow", u"\u5927\u5199\u82f1\u6587\u5b57\u7b26", None))
        self.checkBox_EnglishLower.setText(QCoreApplication.translate("MainWindow", u"\u5c0f\u5199\u82f1\u6587\u5b57\u7b26", None))
        self.checkBox_EnglishPunctuation.setText(QCoreApplication.translate("MainWindow", u"\u82f1\u6587\u6807\u70b9", None))
        self.pushButton_textCleaningSetting.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u591a\u8bbe\u7f6e", None))
        self.tabWidget_modelChoice.setTabText(self.tabWidget_modelChoice.indexOf(self.tab_0), QCoreApplication.translate("MainWindow", u"\u6587\u672c\u6e05\u6d17", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5927\u8bcd\u8bed\u957f\u5ea6\uff1a", None))
        self.pushButton_wordMiningSetting.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u591a\u8bbe\u7f6e", None))
        self.tabWidget_modelChoice.setTabText(self.tabWidget_modelChoice.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"\u8bcd\u8bed\u6316\u6398", None))
        self.pushButton_cutWordSetting.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u591a\u8bbe\u7f6e", None))
        self.comboBox_cutWordModelSelect.setItemText(0, QCoreApplication.translate("MainWindow", u"\u7cbe\u786e\u6a21\u5f0f", None))
        self.comboBox_cutWordModelSelect.setItemText(1, QCoreApplication.translate("MainWindow", u"\u5168\u6a21\u5f0f", None))
        self.comboBox_cutWordModelSelect.setItemText(2, QCoreApplication.translate("MainWindow", u"\u641c\u7d22\u5f15\u64ce\u6a21\u5f0f", None))
        self.comboBox_cutWordModelSelect.setItemText(3, QCoreApplication.translate("MainWindow", u"\u8bcd\u6027\u7b5b\u9009\u6a21\u5f0f", None))
        self.comboBox_cutWordModelSelect.setItemText(4, QCoreApplication.translate("MainWindow", u"\u5173\u952e\u8bcd\u62bd\u53d6\u6a21\u5f0f (TextRank)", None))
        self.comboBox_cutWordModelSelect.setItemText(5, QCoreApplication.translate("MainWindow", u"\u5173\u952e\u8bcd\u62bd\u53d6\u6a21\u5f0f (TF-IDF)", None))

        self.label_cutModelExtraction.setText(QCoreApplication.translate("MainWindow", u"\u62bd\u53d6\u91cf\uff1a", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u5206\u8bcd\u6a21\u578b\uff1a", None))
        self.checkBox_wordFrequency.setText(QCoreApplication.translate("MainWindow", u"\u7edf\u8ba1\u8bcd\u9891", None))
        self.tabWidget_modelChoice.setTabText(self.tabWidget_modelChoice.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u6587\u672c\u5206\u8bcd", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u9608\u503c\uff1a", None))
        self.comboBox_textClusteringModelSelect.setItemText(0, QCoreApplication.translate("MainWindow", u"K \u5747\u503c\u805a\u7c7b-\u81ea\u5b9a\u7c7b\u76ee\u6570\u91cf", None))
        self.comboBox_textClusteringModelSelect.setItemText(1, QCoreApplication.translate("MainWindow", u"\u5c42\u6b21\u805a\u7c7b-\u81ea\u5b9a\u8ddd\u79bb\u9608\u503c", None))
        self.comboBox_textClusteringModelSelect.setItemText(2, QCoreApplication.translate("MainWindow", u"\u5c42\u6b21\u805a\u7c7b-\u81ea\u5b9a\u7c7b\u76ee\u6570\u91cf", None))

        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u5206\u8bcd\u6a21\u578b\uff1a", None))
        self.tabWidget_modelChoice.setTabText(self.tabWidget_modelChoice.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u6587\u672c\u805a\u7c7b", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u6587\u672c\u5217\uff1a", None))
        self.comboBox_wordCloudText.setItemText(0, QCoreApplication.translate("MainWindow", u"\u8bf7\u9009\u62e9\u4e00\u5217\u6570\u636e", None))

        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u5bbd\u5ea6\uff1a", None))
        self.pushButton_wordCloudSetting.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u591a\u8bbe\u7f6e", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u8bcd\u9891\u5217\uff1a", None))
        self.comboBox_wordCloudRank.setItemText(0, QCoreApplication.translate("MainWindow", u"\u8bf7\u9009\u62e9\u4e00\u5217\u6570\u636e", None))

        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u9ad8\u5ea6\uff1a", None))
        self.pushButton_makeWordCloud.setText(QCoreApplication.translate("MainWindow", u"\u5236\u4f5c", None))
        self.pushButton_viewWordCloud.setText(QCoreApplication.translate("MainWindow", u"\u9884\u89c8", None))
        self.tabWidget_modelChoice.setTabText(self.tabWidget_modelChoice.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u8bcd\u4e91\u56fe\u5236\u4f5c", None))
        self.file_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menu_save.setTitle(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa", None))
        self.menu_table.setTitle(QCoreApplication.translate("MainWindow", u"\u6570\u636e", None))
        self.menu_image.setTitle(QCoreApplication.translate("MainWindow", u"\u56fe\u7247", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3", None))
    # retranslateUi

